### ISSUE TITLE
v0.4.1: Instrumentation breaks function references in cmd/vk-gen/main.go

### ISSUE THREAD

**Issue by kolkov** [kolkov/racedetector#9]
## Environment
- **racedetector version**: v0.4.1
- **Go version**: 1.25
- **OS**: Ubuntu (GitHub Actions ubuntu-latest)
- **CGO_ENABLED**: 0

## Description

After updating to v0.4.1 (which fixed #8), a new issue appeared: the instrumentation phase corrupts function references, causing compilation errors like:

```
invalid operation: cannot take address of parseSpec (value of type func...)
make (built-in) must be called
string (type) is not an expression
```

## Steps to Reproduce

1. Run `racedetector test ./...` on a project containing function references
2. See compilation errors after instrumentation

## Expected Behavior

Instrumentation should preserve valid Go syntax for function references.

## Actual Behavior

Function references are corrupted during instrumentation, causing:
- `cannot take address of <function>`
- `(built-in) must be called`
- `(type) is not an expression`

## CI Run

- Job: https://github.com/gogpu/wgpu/actions/runs/20082250820/job/57611849122
- PR: https://github.com/gogpu/wgpu/pull/1

## Affected File

`cmd/vk-gen/main.go` - contains function references that get corrupted during instrumentation.

## Related

Follows fix for #8 (directory prefix issue).

**Comment by kolkov** [comment]
Tested v0.4.2 - same issue persists.

```
cannot take address of wgl.NewContext (value of type func...)
cannot take address of os.ReadFile (value of type func...)
cannot take address of strconv.ParseInt (value of type func...)
```

CI run: https://github.com/gogpu/wgpu/actions/runs/20082742516
